### ISSUE TITLE
Remove old datasets

### ISSUE THREAD

**Issue by FrancescAlted** [statkraft/shyft-data#3]
After PR https://github.com/statkraft/shyft/pull/24 was included, and at the request of @felixmatt, the next files are not necessary anymore should be removed permanently:

https://github.com/statkraft/shyft-data/blob/master/netcdf/orchestration-testdata/cell_info.nc
https://github.com/statkraft/shyft-data/blob/master/netcdf/orchestration-testdata/stations_discharge.nc
https://github.com/statkraft/shyft-data/blob/master/netcdf/orchestration-testdata/stations_met.nc

The history in git should be removed too.  [BFG repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/) should work well for that purpose.  I don't have privileges for doing that in this repo, so either I get privileges or the current owners should do that.  Thanks!

**Comment by skavhaug** [comment]
Done.
